### ISSUE TITLE
Feature request: saving simulated data

### ISSUE THREAD

**Issue by joshuategegne1** [MLGlobalHealth/bayes-rate-consistency#2]
Hi Shozen,

We're Year 4 Msci students supervised under Oliver and are working with the bayes rate consistency model! We tried to run some scripts from this repo and had some minor issues that might be of your interest;

In parser ensure that data is set before strata is defined-  in sim-run-stan.R
(Line 48 should be after 52)

Could you please specify an outdir directory in the parser when you simulate the data, and ideally this should be outside the repo. 

Many thanks,

Joshua, Cristian and Selena

**Comment by ShozenD** [comment]
Hi Joshua, Cristian, and Selena

Thank you for raising the issue and thank you for your interest.
I will get this fixed ASAP and notify you through this thread.

Shozen

**Comment by ShozenD** [comment]
Hello Joshua, Cristian, and Selena

I have included a few lines in the parser s.t. you can specify the output directory of the fitted model using --out_dir option.
Note that you may also have to add --out_dir option when you run the sim-postprocess.R or else the script will not know where the fitted Stan models lie.

Additionally, I have included a tutorial on how to run the simulated experiments under tutorials/simulation-experiments.Rmd

Thanks again for raising the issue and happy to answer any additional questions.

Shozen
